# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 907dc3a66542c50c0711b37dda56bb00a2f73ee26020d8e7467f428a1ef85aae52a6a93874b5a2e723ceae8da97804e9ec54890f55744484dbd5a78a7bfd7b14

test:
  secret_key_base: 81592aa5e8c3500b010d81e16ca55d4daf56f210fc564e8bd5aa5b8ffa059e8339ca13f2b34b89b28aec034a1beaaa1861b26a2dca6d77212c3665290104cf00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
